x-build-args: &build_args
  INSTALL_PYTHON_VERSION: "3.12.8"
  INSTALL_NODE_VERSION: "22.14.0"

x-default-volumes: &default_volumes
  volumes:
    - ./:/app
    - node-modules:/app/node_modules
    - dev-data:/app/dev.db


services:
  flask-dev:
    build:
      context: .
      target: development
      args:
        <<: *build_args
    image: "app-development"
    ports:
      - "8080:5000"
      - "2992:2992"
    env_file: .env         
    <<: *default_volumes

  flask-prod:
    build:
      context: .
      target: production
      args:
        <<: *build_args
    image: "app-production"
    ports:
      - "8080:5000"
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: 0
      LOG_LEVEL: info
      GUNICORN_WORKERS: 4
    env_file: .env          
    <<: *default_volumes

  manage:
    build:
      context: .
      target: development
      args:
        <<: *build_args
    entrypoint: flask
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: 0
    env_file: .env            
    image: "app-manage"
    stdin_open: true
    tty: true
    <<: *default_volumes

volumes:
  node-modules:
  dev-data:
