"""empty message

Revision ID: 1b2c7b324f1e
Revises: 953bbe555076
Create Date: 2025-04-10 09:25:25.455505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b2c7b324f1e'
down_revision = '953bbe555076'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_access_dashboard', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_pilot_robot', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_view_history', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('can_view_history')
        batch_op.drop_column('can_pilot_robot')
        batch_op.drop_column('can_access_dashboard')

    # ### end Alembic commands ###
